version: "3.8"

services:
    app:
        build: .
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"
        environment:
            - APP_ENV=local
            - APP_KEY=base64:php artisan key:generate --show
            - DB_HOST=db
            - DB_DATABASE=app
            - DB_USERNAME=app
            - DB_PASSWORD=secret
        depends_on:
            - db

    db:
        image: mysql:8
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
